name: srila_prabhupada_books
description: "SRILA PRABHUPADA'S BOOK - HARE KRISHNA"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  flutter_screen_wake: ^1.0.2
  share_plus: ^7.2.1
  launch_review: ^3.0.1
  shared_preferences: ^2.2.2
  flutter_material_color_picker: ^1.2.0
  country_code_picker: ^3.0.0
  flutter_tts: ^3.8.5
  lottie: ^2.7.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/main_database.db
    - assets/bookmark.db
    - assets/db_highlight.db
    - assets/images/
    - assets/Language/
    - assets/book_images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Poppins-Black.ttf
          weight: 900
        - asset: fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

